### ISSUE TITLE
Processing Steps

### ISSUE THREAD

**Issue by kevinmchu** [jbilskie/BME547_final#34]
@xc130 @jbilskie I modified the client and the server to perform multiple processing steps on an uploaded image ( #33). The proc_step variable is replaced with proc_steps, which is a list of Booleans that specify whether a processing step should be performed.

**Comment by xinlin-chen** [comment]
@kevinmchu get_img_size currently returns the dimensions in the order (height, width), instead of (width, height) - I'll change it to the right order

**Comment by kevinmchu** [comment]
Okay.

**Comment by xinlin-chen** [comment]
@kevinmchu @jbilskie since proc_steps is now a list of booleans, can we also make it so the image is stored at the location related to those processing steps? like we could have / <img_filename> /1100.<file_ext> if only the first two processing steps were requested, for example, and then download from that location using the get request.

**Comment by xinlin-chen** [comment]
@kevinmchu @jbilskie FYI I'll make it so if a zip is entered, the filenames of the images inside are returned alongside the images themselves

**Comment by jbilskie** [comment]
I have all images save as 'filename''processing step'.'desired extension' and the location is an argument. Is that okay, @xc130 ?

**Comment by xinlin-chen** [comment]
@jbilskie I updated this so that filename now excludes any '.jpg', '.png' etc and there is a space between filename and processing step
