### ISSUE TITLE
Server - Test Image Download and Display

### ISSUE THREAD

**Issue by kevinmchu** [jbilskie/BME547_final#48]
Write unit tests for
`upload_processed_image`
`process_image_download`
`exist_input`
`delete_user`
`delete_img`

**Comment by kevinmchu** [comment]
@jbilskie Are you finished with the image download code? If so, I will start testing your functions.

**Comment by jbilskie** [comment]
@kevinmchu u I need to write a function to download the picture as either tiff jpeg, or png. I'll try to get that done today and then those functions should be good and the rest of the functionality I have assigned to me should fall under functions.

Sorry..... it took a while figuring out how to download images because if you use too big of a picture (which the flowchart we have is) and then use certain processing on it and it becomes larger, then MongoDB won't accept it because the command is too large.

**Comment by kevinmchu** [comment]
Sounds good.

**Comment by jbilskie** [comment]
@kevinmchu Actually image type conversion happens in image.py. The server just returns a b64 of the image. So yes those functions should be good to go.

**Comment by xinlin-chen** [comment]
@jbilskie @kevinmchu the instructions also say that multiple images should be downloaded as a ZIP archive, how should we deal with that?

**Comment by kevinmchu** [comment]
@xc130 Once we have a list of images, we could pass them to a function that zips them.

**Comment by kevinmchu** [comment]
Done. #100
