### ISSUE TITLE
Processed image handling

### ISSUE THREAD

**Issue by xinlin-chen** [jbilskie/BME547_final#6]

**Comment by kevinmchu** [comment]
Finished code to process and upload images.

**Comment by jbilskie** [comment]
@kevinmchu When we upload a processed image, don't we also want to upload its original? As written, it appears that the class User will never have anything in proc_img because it always uploads to orig_img. Can I change this so that when processing is done, the original image is saved in orig_img of User class and the processed image is in proc_img?

**Comment by kevinmchu** [comment]
Good call. Go ahead and make the modification.

**Comment by kevinmchu** [comment]
I believe this is finished.
